### ISSUE TITLE
стр Каталог: подправить заголовки, маркеры списков

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-teploelement-met#96]
http://prntscr.com/kyi5y6
нужно: http://prntscr.com/kyi6j3

**Comment by VladyslavKovalchuk** [comment]
http://prntscr.com/kz0c41 еще этот

**Comment by VladyslavKovalchuk** [comment]
еще нужно выделить выделенный текст http://prntscr.com/kze16c

**Comment by Derevyanchenko** [comment]
этот текст выделяется заказчиком из админки (а не верстальщиком)
