### ISSUE TITLE
Зафиксировать размеры блока превью новости на главной

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-teploelement-met#99]
http://prntscr.com/kyu15m
сделать, чтоб при меньшем количестве текста в заголовке и в новости размер блока заголовка и размер блока текста новости был фиксированным. Так же добавить ограничение по символам для превью.
http://prntscr.com/kyu1o2

**Comment by maxis55** [comment]
Добавил ограничение на главной 74 символа и на странице новостей 163 символа. Теперь нужно front поправить
